name: 'Publish'
on:
  pull_request:
    branches: 
      - main
    types: [closed]
  # workflow_dispatch
  # push:
  #    branches:
  #      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4 # Updated to latest version for better compatibility
      - name: Setup Node.js
        uses: actions/setup-node@v4 # Updated to latest version
        with:
          node-version: 20 # Upgraded from 16 (EOL) to a supported version
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev librsvg2-dev patchelf
      - name: Install frontend dependencies
        run: yarn install # Adjust to npm or pnpm if needed
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # Automatically replaces __VERSION__ with app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
